name: React app deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up React 
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy React app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd ~/uy-joy-baraka
            git pull
            npm run build
            cp -rf ~/uy-joy-baraka/dist/* /var/www/uyjoybaraka.uz